/// Flutter icons PlantIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlantIcons
///      fonts:
///       - asset: fonts/PlantIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PlantIcons {
  PlantIcons._();

  static const _kFontFam = 'PlantIcons';
  static const String? _kFontPkg = null;

  static const IconData profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vibrate = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grape_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wave = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
